version: 2

sources:
  - name: raw
    database: CONTENT_ANALYTICS
    schema: RAW
    tables:
      - name: movies
      - name: ratings
      - name: tags
      - name: links
      - name: tmdb_metadata